Delete www/_assets/images/pyladies_cochabamba.png:Zone.Identifier
Causing error during Git Clone:
error: invalid path 'www/_assets/images/pyladies_cochabamba.png:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.